using System.Diagnostics.CodeAnalysis;

// DllImport is fine for infrequently-called P/Invoke methods
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.CursorIndicator.LoadImage(System.IntPtr,System.UInt32,System.UInt32,System.Int32,System.Int32,System.UInt32)~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.CursorIndicator.CopyIcon(System.IntPtr)~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.CursorIndicator.SetSystemCursor(System.IntPtr,System.UInt32)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.CursorIndicator.SystemParametersInfo(System.UInt32,System.UInt32,System.IntPtr,System.UInt32)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.HotkeyService.RegisterHotKey(System.IntPtr,System.Int32,System.UInt32,System.UInt32)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.HotkeyService.UnregisterHotKey(System.IntPtr,System.Int32)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.TextCaptureService.keybd_event(System.Byte,System.Byte,System.UInt32,System.UIntPtr)")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.TextCaptureService.GetForegroundWindow~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.TextCaptureService.GetAsyncKeyState(System.Int32)~System.Int16")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.TextCaptureService.GetClipboardSequenceNumber~System.UInt32")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "DllImport is sufficient for this use case", Scope = "member", Target = "~M:LocalTTS.Services.TextCaptureService.GetOpenClipboardWindow~System.IntPtr")]
